### ISSUE TITLE
Support for Column names with space

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [shinichi-takii/ddlparse#54]
Sometimes we may have column names space that is not working.

### Reproduce the issue:

```py
from ddlparse import DdlParse

sample_ddl = """
CREATE TABLE IF NOT EXISTS stage2.tbl
(
	id VARCHAR(36) NOT NULL  ENCODE RAW
		,"lead id" VARCHAR(50)   ENCODE RAW
	,PRIMARY KEY (id)
)
DISTSTYLE AUTO
;


"""

# parse pattern (1)
table = DdlParse().parse(sample_ddl)

# parse pattern (2)
parser = DdlParse()
parser.ddl = sample_ddl
table = parser.parse()

print("* TABLE *")
print("schema = {} : name = {} : is_temp = {}".format(table.schema, table.name, table.is_temp))

print("* BigQuery Fields *")
print(table.to_bigquery_fields())

print("* BigQuery Fields - column name to lower case / upper case *")
print(table.to_bigquery_fields(DdlParse.NAME_CASE.lower))
print(table.to_bigquery_fields(DdlParse.NAME_CASE.upper))

print("* COLUMN *")
for col in table.columns.values():
    print("name = {} : data_type = {} : length = {} : precision(=length) = {} : scale = {} : constraint = {} : not_null =  {} : PK =  {} : unique =  {} : BQ {}".format(
        col.name,
        col.data_type,
        col.length,
        col.precision,
        col.scale,
        col.constraint,
        col.not_null,
        col.primary_key,
        col.unique,
        col.to_bigquery_field()
        ))
```

### Error:
```py
Traceback (most recent call last):
  File "bqconverter.py", line 280, in <module>
    main()
  File "bqconverter.py", line 273, in main
    redshift_file_conversion(infile)
  File "bqconverter.py", line 151, in redshift_file_conversion
    target_type = data_mapping[source_type]
KeyError: 'id'
```

**Comment by shinichi-takii** [comment]
@BhuviTheDataGuy 
Fixed this issue in `v1.7.0`
